server:
  port: 8087
  address: 0.0.0.0
  servlet:
    context-path: /

spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://49.235.98.213:3306/tcc_order?useUnicode=true&characterEncoding=utf8
        username: ocean
        password: ocean

org:
    dromara:
         hmily :
            serializer : kryo
            recoverDelayTime : 1000
            retryMax : 30
            scheduledDelay : 1000
            scheduledThreadMax :  10
            repositorySupport : db
            started: true
            async-threads: 10
            hmilyDbConfig :
                 driverClassName  : com.mysql.jdbc.Driver
                 url :  jdbc:mysql://49.235.98.213:3306/tcc?useUnicode=true&characterEncoding=utf8
                 username : ocean
                 password : ocean

        #repositorySupport : redis
        #tccRedisConfig:
                # masterName: mymaster
                 #sentinel : true
                 #sentinelUrl : 192.168.1.91:26379;192.168.1.92:26379;192.168.1.93:26379
                # password  : foobaredbbexONE123

mybatis:
  type-aliases-package: com.hmily.tcc.demo.dubbo.order.entity
  config-location: classpath:mybatis/mybatis-config.xml

logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: info
        org.dromara.hmily.bonuspoint: info
        org.dromara.hmily.lottery: info
        org.dromara.hmily: info
        io.netty: info
    path: "./logs"

